version: "3"
services:
  app:
    build:
      args:
       user: trainer
       uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - db
    ports:
     - "127.0.0.1:8080:80"

  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pokemon
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    depends_on:
      - db
      - app
